from project.bakery import Bakery

bakery = Bakery("Alinas's")
bakery_2 = Bakery("Marina's")
print(bakery.add_food('Bread', 'Carrot', 10))
print(bakery.add_food("Cake", "torta", 50.00))
print(bakery.add_table("InsideTable", 10, 5))
print(bakery.add_food("Bread", "franzela", 20.00))
print(bakery.add_food("Cake", "garash", 80.00))
print(bakery.reserve_table(4))
print(bakery.order_food(10, "franzela", "torta", "supa", "pizza"))
print(bakery.add_drink("Tea", "studen chai", 200, "Icetea"))
print(bakery.add_drink("Water", "trapezna voda", 100, "Bankq"))
print(bakery.order_drink(10, "trapezna voda", "kola", "kokteil", "studen chai"))
print(bakery.leave_table(10))
print(bakery.add_table("OutsideTable", 55, 3))
print(bakery.get_free_tables_info())
print(bakery.get_total_income())
print(bakery.reserve_table(2))
